---
title: "knitr with pdf_document2"
output:
  bookdown::pdf_document2:
    keep_tex: yes
    latex_engine: pdflatex
  html_notebook: default
---


```{r setup, include=FALSE, error=TRUE, message=FALSE, warning=FALSE} 
knitr::opts_chunk$set(echo = FALSE, 
                      comment = NA, 
                      error = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.align = 'center',
                      results = "asis"
                      )

options(knitr.table.format = "html") 
```

```{r load_libraries, message=FALSE}
library(knitr)
library(kableExtra)
library(ggplot2)
```


Refer to Fig. \@ref(fig:fig-margin).

```{r subsetmtcars}
knitr::kable(mtcars[1:6, 1:6], caption = 'A subset of mtcars.')
```

```{r fig-margin,  fig.cap = "MPG vs horsepower, colored by transmission."}

mtcars2 <- mtcars
mtcars2$am <- factor(
  mtcars$am, labels = c('automatic', 'manual')
)
ggplot(mtcars2, aes(hp, mpg, color = am)) +
  geom_point() + geom_smooth() +
  theme(legend.position = 'bottom')
```

Table \@ref(tab:subsetmtcars)




