---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, error=TRUE, message=FALSE, warning=FALSE} 
knitr::opts_chunk$set(echo=TRUE, 
                      comment=NA, 
                      error=TRUE, 
                      warning=FALSE, 
                      message = FALSE, 
                      results = "asis",
                      fig.align = 'center')
```

https://stackoverflow.com/questions/43412497/combining-multiple-summary-tables-with-subheadings

```{r}
library(expss)
library(knitr)

dd = data.frame(barcode = c("16929", "64605", "03086", "29356", "23871"),
                 sex = factor(c("M", "F", "M", "F", "M")), 
                 marital = factor(c("Married", "Single", "Single", "Single", "Divorced")),
                 age_group = factor(c("<25", "25-34", "35-44", "45-54", ">= 55"), 
                                    levels = c("<25", "25-34", "35-44", "45-54", ">= 55")))


dd %>% tab_cells("Sex" = sex, "Marital status" = marital, "Age" = age_group) %>% 
    tab_cols(total(label = "N")) %>% 
    tab_stat_cases(total_row_position = "none") %>% 
    tab_pivot()
```


```{r}
dd %>% tab_cells("Sex" = sex, "Marital status" = marital, "Age" = age_group) %>% 
    tab_cols(total(label = "N")) %>% 
    tab_stat_cases(total_row_position = "none") %>% 
    tab_pivot() %>% 
    split_columns() %>% 
    kable()
```



