---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---

Works in:
* Html
* PDF
* Notebook

```{r}
options(digits = 4)
set.seed(123)
x = matrix(rnorm(40), 5)
dimnames(x) = list(NULL, head(LETTERS, ncol(x)))
knitr::kable(x, digits = 2, caption = "A table produced by printr.")
```
This library doesn't work

```{r}
library(printr)

options(digits = 4)
set.seed(123)
x = matrix(rnorm(40), 5)
x
```
```{r}
# with colunm names
dimnames(x) = list(NULL, head(LETTERS, ncol(x)))
x
```



```{r}
# further customization via kable(), e.g. digits and captions
knitr::kable(x, digits = 2, caption = 'A table produced by printr.')
```
```{r}
# further customization via kable(), e.g. digits and captions
knitr::kable(x, digits = 2, caption = 'A table produced by printr.')
```
```{r}
head(mtcars)
```

```{r}
head(iris, 10)
```

```{r}
x1 = sample(letters[1:3], 1000, TRUE)
x2 = sample(letters[1:3], 1000, TRUE)
x3 = sample(letters[1:3], 1000, TRUE)
table(x1)
```

```{r}
browseVignettes(package='knitr')
```

